# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adam/Liquid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adam/Liquid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/Liquid/CMakeFiles /home/adam/Liquid/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/Liquid/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named liquid

# Build rule for target.
liquid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 liquid
.PHONY : liquid

# fast build rule for target.
liquid/fast:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/build
.PHONY : liquid/fast

src/context.o: src/context.cpp.o

.PHONY : src/context.o

# target to build an object file
src/context.cpp.o:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/context.cpp.o
.PHONY : src/context.cpp.o

src/context.i: src/context.cpp.i

.PHONY : src/context.i

# target to preprocess a source file
src/context.cpp.i:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/context.cpp.i
.PHONY : src/context.cpp.i

src/context.s: src/context.cpp.s

.PHONY : src/context.s

# target to generate assembly for a file
src/context.cpp.s:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/context.cpp.s
.PHONY : src/context.cpp.s

src/dialect.o: src/dialect.cpp.o

.PHONY : src/dialect.o

# target to build an object file
src/dialect.cpp.o:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/dialect.cpp.o
.PHONY : src/dialect.cpp.o

src/dialect.i: src/dialect.cpp.i

.PHONY : src/dialect.i

# target to preprocess a source file
src/dialect.cpp.i:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/dialect.cpp.i
.PHONY : src/dialect.cpp.i

src/dialect.s: src/dialect.cpp.s

.PHONY : src/dialect.s

# target to generate assembly for a file
src/dialect.cpp.s:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/dialect.cpp.s
.PHONY : src/dialect.cpp.s

src/interface.o: src/interface.cpp.o

.PHONY : src/interface.o

# target to build an object file
src/interface.cpp.o:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/interface.cpp.o
.PHONY : src/interface.cpp.o

src/interface.i: src/interface.cpp.i

.PHONY : src/interface.i

# target to preprocess a source file
src/interface.cpp.i:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/interface.cpp.i
.PHONY : src/interface.cpp.i

src/interface.s: src/interface.cpp.s

.PHONY : src/interface.s

# target to generate assembly for a file
src/interface.cpp.s:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/interface.cpp.s
.PHONY : src/interface.cpp.s

src/optimizer.o: src/optimizer.cpp.o

.PHONY : src/optimizer.o

# target to build an object file
src/optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/optimizer.cpp.o
.PHONY : src/optimizer.cpp.o

src/optimizer.i: src/optimizer.cpp.i

.PHONY : src/optimizer.i

# target to preprocess a source file
src/optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/optimizer.cpp.i
.PHONY : src/optimizer.cpp.i

src/optimizer.s: src/optimizer.cpp.s

.PHONY : src/optimizer.s

# target to generate assembly for a file
src/optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/optimizer.cpp.s
.PHONY : src/optimizer.cpp.s

src/parser.o: src/parser.cpp.o

.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/renderer.o: src/renderer.cpp.o

.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i

.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s

.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/web.o: src/web.cpp.o

.PHONY : src/web.o

# target to build an object file
src/web.cpp.o:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/web.cpp.o
.PHONY : src/web.cpp.o

src/web.i: src/web.cpp.i

.PHONY : src/web.i

# target to preprocess a source file
src/web.cpp.i:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/web.cpp.i
.PHONY : src/web.cpp.i

src/web.s: src/web.cpp.s

.PHONY : src/web.s

# target to generate assembly for a file
src/web.cpp.s:
	$(MAKE) -f CMakeFiles/liquid.dir/build.make CMakeFiles/liquid.dir/src/web.cpp.s
.PHONY : src/web.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... liquid"
	@echo "... src/context.o"
	@echo "... src/context.i"
	@echo "... src/context.s"
	@echo "... src/dialect.o"
	@echo "... src/dialect.i"
	@echo "... src/dialect.s"
	@echo "... src/interface.o"
	@echo "... src/interface.i"
	@echo "... src/interface.s"
	@echo "... src/optimizer.o"
	@echo "... src/optimizer.i"
	@echo "... src/optimizer.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/web.o"
	@echo "... src/web.i"
	@echo "... src/web.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

